application: your-application-id-here
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/css/\1
  upload: static/css/(.*\.css)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(external.*\.py)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.py)

- url: /(caras.*\.py)
  mime_type: text/plain
  static_files: src/main/python/client/\1
  upload: src/main/python/client/(.*\.py)

- url: /(libs.*\.py)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.py)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png|svg))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png|svg))

- url: .*  # This regex directs all routes to main.app
  script: src.main.python.main.bottle

# Third party libraries that are included in the App Engine SDK must be listed
# here if you want to use them.  See
# https://developers.google.com/appengine/docs/python/tools/libraries27 for
# a list of libraries included in the SDK.  Third party libs that are *not* part
# of the App Engine SDK don't need to be listed here, instead add them to your
# project directory, either as a git submodule or as a plain subdirectory.
# Note that dependencies must be located in your project directory - packages
# installed in the Python environment are not loaded by the App Engine development
# server or deployment tools.
# TODO: List any other App Engine SDK libs you may need here.
libraries:
- name: jinja2
  version: latest
